apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml

images:
  - name: {{image}}
    newName: {{image}}
    newTag: dev

configMapGenerator:
  - name: {{service-name}}-config
    literals:
      - NODE_ENV=development
      - PORT=3000

secretGenerator:
  - name: {{service-name}}-secret
    literals:
      - JWT_SECRET=replace-with-secret

commonLabels:
  environment: dev
