apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - production-stack.yaml
  - backup-cronjob.yaml
  - enterprise-ops.yaml
  - ../base/grafana

images:
  - name: ghcr.io/shivanshuyadav921/shop/auth-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/invoice-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/payment-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/wallet-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/fraud-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/ledger-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/compliance-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/analytics-service
    newTag: latest
  - name: ghcr.io/shivanshuyadav921/shop/audit-service
    newTag: latest

configMapGenerator:
  - name: shop-platform-config
    literals:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=shop
      - DATABASE_NAME=shop_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - PROMETHEUS_HOST=prometheus
      - GRAFANA_HOST=grafana

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      platform: shop
      environment: production
    includeSelectors: false
